"""P5 gate regression guard against the adversarial red-team corpus.

``tests/fixtures/read_pi_corpus.json`` is 116 natural-language prompt-injection
payloads + 113 near-boundary benign samples, generated by a multi-agent red-team
across source types (README, GitHub issue, dependency doc, web page, MCP output,
security doc, multilingual, polite-indirect). These tests lock in the suspicion
gate's measured operating point so a future regex edit cannot silently gut recall
or balloon false positives.

Operating point at authoring time: ~93% incremental recall on regex-missed
attacks; ~5% false positives on non-meta benign content. Thresholds below leave
margin so legitimate tuning does not trip them.

NOTE: most residual benign false positives are *security documentation* that
quotes live attack strings — that is by design the LLM backstop's job, not the
cheap gate's, so those kinds are excluded from the FP guard.
"""
from __future__ import annotations

import json
from pathlib import Path

from ccguard.agent.prompt_injection_engine import scan as strict_scan
from ccguard.agent.read_pi_escalation import should_escalate
from ccguard.schemas.policy import PromptInjectionConfig

_CFG = PromptInjectionConfig()  # strict catalog only (llama_guard off by default)
_META_KINDS = {"security-doc", "blog-post", "incident-report", "security-advisory", "ctf-writeup"}
_CORPUS = json.loads(
    (Path(__file__).parent.parent / "fixtures" / "read_pi_corpus.json").read_text(encoding="utf-8")
)


def _strict_hits(text: str) -> bool:
    r = strict_scan(text, _CFG)
    return r is not None and r.rule_id != "prompt_injection.llama_guard.model_missing"


def test_gate_incremental_recall_on_regex_missed_attacks():
    """The gate must escalate ≥85% of injection payloads the strict catalog misses."""
    attacks = _CORPUS["attacks"]
    strict_missed = [a for a in attacks if not _strict_hits(a["text"])]
    assert strict_missed, "corpus should contain regex-missed attacks"
    caught = sum(1 for a in strict_missed if should_escalate(a["text"]))
    recall = caught / len(strict_missed)
    assert recall >= 0.85, f"gate incremental recall {recall:.1%} < 85% ({caught}/{len(strict_missed)})"


def test_gate_false_positive_rate_on_non_meta_benign():
    """The gate must NOT escalate >15% of ordinary (non-security-doc) benign content."""
    benign = [b for b in _CORPUS["benign"] if b.get("kind") not in _META_KINDS]
    assert benign, "corpus should contain non-meta benign samples"
    fp = sum(1 for b in benign if should_escalate(b["text"]))
    rate = fp / len(benign)
    assert rate <= 0.15, f"non-meta benign false-positive rate {rate:.1%} > 15% ({fp}/{len(benign)})"
