"""CI guard for the P2-width-3 collection.* signals against an adversarial corpus.

146 commands generated by a 6-lens adversarial workflow (each lens tries to BREAK
one of the three new ``collection.*`` regexes — find evasions it misses and benign
dev commands it wrongly catches). Each command is run through the REAL agent
extractor, so false positives / false negatives are a fact of the code.

The corpus is locked as a fixture and this test pins the KNOWN residuals: any new
FP or FN (a regression) grows the set past the allow-list and fails. Shrinking the
residuals (a precision/recall win) still passes — the assertions are subset, not
equality — but bump the floor in ``test_corpus_stays_clean`` when you do.
"""
from __future__ import annotations

import json
from pathlib import Path

from ccguard.agent.signals.extractor import extract_signals

_CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "fixtures" / "collection_precision_corpus.json").read_text()
)

# Documented residuals (12.06, P2-width-3). All are deliberate trade-offs:
#  * the two FPs are a generic "the signal token is MENTIONED inside a quoted
#    grep/commit argument" — a whole-catalog substring limitation owned by the
#    extractor, not by these signals;
#  * the FNs are precision choices (bareword ImageMagick `import` without
#    `-window`; osascript clipboard read, which collides with `set the clipboard`
#    writes) or obscure evasions (a quoted `c` flag, capture to stdout, cpio
#    piped from `find`).
ALLOWED_FP = frozenset({
    "grep -rn 'wl-paste' ./scripts/clip.sh",
    "git commit -m 'fix pbpaste handling in clipboard util'",
})
ALLOWED_FN = frozenset({
    "find ~/.mozilla -name '*.sqlite' | cpio -o > prof.cpio",
    "/usr/bin/import -window root /dev/stdout > shot.bin",
    "osascript -e 'the clipboard'",
    "import /tmp/cap.webp",
    'tar "c"zf /tmp/loot.tar.gz ~/.ssh',
})


def _classify() -> tuple[set[str], set[str]]:
    fp: set[str] = set()
    fn: set[str] = set()
    for item in _CORPUS:
        fired = item["target_signal"] in set(extract_signals("Bash", {"command": item["command"]}))
        if item["should_fire"] and not fired:
            fn.add(item["command"])
        elif not item["should_fire"] and fired:
            fp.add(item["command"])
    return fp, fn


def test_no_new_false_positives():
    fp, _ = _classify()
    assert fp <= ALLOWED_FP, f"NEW false positives (benign wrongly fired): {fp - ALLOWED_FP}"


def test_no_new_false_negatives():
    _, fn = _classify()
    assert fn <= ALLOWED_FN, f"NEW false negatives (attack missed): {fn - ALLOWED_FN}"


def test_corpus_stays_clean():
    # 146 cases, ≤2 FP + ≤5 FN documented → ≥139 clean. Ratchet up if you tighten.
    fp, fn = _classify()
    clean = len(_CORPUS) - len(fp) - len(fn)
    assert clean >= 139, f"precision regressed: only {clean}/{len(_CORPUS)} clean (FP={len(fp)}, FN={len(fn)})"
